env:
  global:
  - CC_TEST_REPORTER_ID=3d807f7c86185098a51700c116833392e9cf9d128d02f4d5a73ef0313533d59e
language: node_js
node_js:
- stable
services:
  - postgresql
addons:
  postgresql: "9.5"
cache:
  directories:
  - node_modules
before_script:
- npm install
- psql -c '\i api/src/migrations/migrate.sql \q' -U postgres
- psql -c "CREATE ROLE fieldinsights WITH LOGIN PASSWORD 'lovely' CREATEDB SUPERUSER;" -U postgres
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
script:
- npm test
- npm run coveralls
- npm run codeClimate
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
